### ISSUE TITLE
Нужно убрать изначальные значения. 

### ISSUE THREAD

**Issue by Inestria** [rfslf/RHEL#12]
На каждом боссе, каждого рейда убирать галочки, немного муторно и чувствую, что придется убирать весьма часто. Кажется, что лучше изначальную расстановку убрать. @Inestria

**Comment by Inestria** [comment]
@

**Comment by rfslf** [comment]
На каждого боса каждого рейда тебе придется что-то выставить, так не все ли равно убирать или ставить галочки, просто можно сделать максимально удобную конфигурацию по умолчанию для всех, я сделал под себя. И забыл отметить, галки каждого босса сохраняются.

**Comment by rfslf** [comment]
Пока дефолтовые значения останутся,
