### ISSUE TITLE
Создать микроокошко аддона

### ISSUE THREAD

**Issue by Inestria** [rfslf/RHEL#13]
Добавить команду [/Rhel mini] - которое откроет окошко содержащее Выбор подземелья, Выбор босса или треша. В случае 3 ComboBox: Выбор Heals | Buffs | Dispells - и кнопку Anounce. В случае 2 ComboBox,а именно подземелья и боссы - реализовать 3 кнопками Anounce.

**Comment by rfslf** [comment]
В общем повторяет issue #9, или я что-то не уловил?

**Comment by rfslf** [comment]
Сделать минимально возможное окно с основными функциями анонса

**Comment by rfslf** [comment]
Добавил в 0.9 beta, тестируем

**Comment by rfslf** [comment]
Работает
