### ISSUE TITLE
Дополнительное поле в Buff anounce

### ISSUE THREAD

**Issue by rfslf** [rfslf/RHEL#4]
"Buff anounce - нужно добавить поле - павшим"@Инестрия

**Comment by rfslf** [comment]
Предлагаю вариант - выставление всех 8 "галок" приводит к выводу сообщение "Buff all groups and fallen"

**Comment by Inestria** [comment]
ноу, нам нужно павшие отдельно. Поскольку прист1 бафает 1-2 группу. Прист2 3-4. Прист3 5-6. Прист4 7-8. Прист5 павших
То есть он не бафает никого кроме павших

**Comment by rfslf** [comment]
Оукай, "Buff all groups or fallen". Рисовать окно, там где нет места очень плохо, а не включать голову когда играешь вообще ужастно, догадаешься что не все группы твои.

**Comment by Inestria** [comment]
cool

**Comment by rfslf** [comment]
Добавил в 0.9 beta, тестируем

**Comment by rfslf** [comment]
Работает
